---
title: "ConsolidateMultiCityData"
output: html_document
date: "2025-05-30"
---

This file combines the datasets from each city into one consolidated file.

```{r}

folder_path <- "../Input Data/"

# Add more cities to draw from
cities <- c(
  "AUTX", 
  "BOMA", 
  "CHIL", 
  "ICIA", 
  "ININ",
  "JAMS",
  "SLMO",
  "TAWA",
  "URIL"
)

# Base dataframe
df <- read.csv(paste0(folder_path, "photo_database_fin_PACA_cleaned.csv"))

# Append all data to be one, consolidated file
for (city in cities) {
  file <- read.csv(paste0(folder_path, "photo_database_fin_", city, "_cleaned.csv"))
  df <- bind_rows(df, file)
  print(nrow(file))
  print(nrow(df))
}

write.csv(df, paste0(folder_path, "multi_city_data_cleaned.csv"), row.names = FALSE)

```

```{r}

# PACA was derived differently
df_PACA <- read.csv(paste0(folder_path, "active_dates.csv"))
df_mul <- read.csv(paste0(folder_path, "multi_city_active_dates.csv"))

# Combine and output into single file
df_mul <- bind_rows(df_PACA, df_mul)

write.csv(df_mul, paste0(folder_path, "all_city_active_dates.csv"), row.names = FALSE)

```

