This file combines cameras from the same site and extracts impervious data

```{r}

# TODO: add comments

library(sf)
library(dplyr)
library(igraph)
library(terra)

```

```{r}

filepath <- "../Input Data/"

file <- read.csv(paste0(filepath, "all_city_active_dates.csv"))

sites <- file %>%
  select(City, locAbbr, Latitude, Longitude) %>%
  distinct(locAbbr, .keep_all = TRUE)

```

```{r}

sites_sf <- st_as_sf(sites, coords = c("Longitude", "Latitude"), crs = 4326)

sites_utm <- st_transform(sites_sf, crs = 32611)

neighbors <- st_is_within_distance(sites_utm, sites_utm, dist = 150)

g <- make_empty_graph(n = nrow(sites_utm), directed = FALSE)

for (i in seq_along(neighbors)) {
  for (j in neighbors[[i]]) {
    if (i < j) {
      g <- add_edges(g, c(i, j))
    }
  }
}

group_ids <- components(g)$membership

sites$cluster_id <- group_ids

site_groups <- sites %>%
  group_by(cluster_id) %>%
  mutate(locAbbr2 = first(locAbbr)) %>%
  ungroup() %>%
  select(-cluster_id)

```

```{r}

impervious_file <- rast("../Input Data/Annual_NLCD_FctImp_2024_CU_C1V1.tif")

cameraSites <- site_groups
cameraSites_v <- vect(cameraSites, geom = c("Longitude", "Latitude"), crs = "EPSG:4326")

cameraSites_v <- project(cameraSites_v, crs(impervious_file))

cameraBuffers <- buffer(cameraSites_v, width = 1000)
impervious_crop <- crop(impervious_file, cameraBuffers)

extractImpBuf <- terra::extract(impervious_crop[[1]], cameraBuffers, fun = mean)

cameraSites$Impervious <- extractImpBuf[,2]

cameraSites <- cameraSites %>%
  group_by(locAbbr2) %>%
  mutate(Impervious = mean(Impervious, na.rm = TRUE)) %>%
  ungroup()

```

```{r}

output_file <- cameraSites %>%
  select(City, locAbbr, locAbbr2, Impervious)

write.csv(output_file, "../Input Data/camera_sites_with_impervious.csv", row.names = FALSE)

```
